import { spawnSync } from "node:child_process";
import {
  chmodSync,
  copyFileSync,
  realpathSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir, userInfo } from "node:os";
import { delimiter, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  harnessBinaryIdentityOnPath,
  harnessRuntimeEnv,
  prepareHarnessCommand,
  resolveHarnessCommandOnPath,
} from "./runtime-env.js";
import { composeSpawnEnv } from "./env-scope.js";
import { killOwnedProcessTree } from "./process-tree.js";

let root: string;
beforeEach(() => {
  root = realpathSync(mkdtempSync(join(tmpdir(), "npm launch with spaces ")));
});
afterEach(() => {
  vi.unstubAllEnvs();
  rmSync(root, { recursive: true, force: true });
});

// Recorded bytes generated by the real npm cmd-shim package, not by the decoder.
const fixtures = fileURLToPath(new URL("./fixtures/npm-launch/", import.meta.url));
function installed(kind = "node", prefix = join(root, "user prefix")) {
  const native = kind === "native";
  const packageRoot = join(prefix, "node_modules", "@fixture", "tool");
  const script = join(packageRoot, "bin", `tool.${native ? "exe" : "cjs"}`);
  mkdirSync(dirname(script), { recursive: true });
  const shebang =
    kind === "node-env"
      ? "#!/usr/bin/env FIXTURE=1 node --no-warnings"
      : kind === "node-options"
        ? "#!/usr/bin/env node --no-warnings"
        : "#!/usr/bin/env node";
  writeFileSync(
    script,
    native
      ? "MZ-fixture"
      : `${shebang}\nconsole.log(JSON.stringify({args:process.argv.slice(2),marker:process.env.MARKER,home:process.env.HOME}));\n`,
  );
  writeFileSync(
    join(packageRoot, "package.json"),
    JSON.stringify({ name: "@fixture/tool", bin: { tool: `bin/tool.${native ? "exe" : "cjs"}` } }),
  );
  const shim = join(prefix, "tool.cmd");
  writeFileSync(
    shim,
    readFileSync(join(fixtures, `${kind}.cmd`), "utf8").replace(/\r?\n/g, "\r\n"),
  );
  const node = join(prefix, "node.exe");
  copyFileSync(process.execPath, node);
  chmodSync(node, 0o755);
  return { prefix, packageRoot, script, shim, node };
}

describe("standard Windows npm launch preparation", () => {
  it.each(["node", "node-current", "node-options", "node-env"])(
    "recognizes actual %s npm output and preserves its selected runtime",
    (kind) => {
      const fixture = installed(kind);
      const fallback = join(root, "later node");
      mkdirSync(fallback);
      copyFileSync(process.execPath, join(fallback, "node.exe"));
      const command = prepareHarnessCommand(
        "tool",
        ["--version"],
        {
          PATH: [fixture.prefix, fallback].join(delimiter),
          HOME: "scoped",
          MARKER: "profile",
          PATHEXT: ".COM;.JS;.EXE;",
        },
        "win32",
      );
      expect(command.binary).toBe(fixture.node);
      expect(command.args).toEqual([
        ...(kind === "node" || kind === "node-current" ? [] : ["--no-warnings"]),
        fixture.script,
        "--version",
      ]);
      expect(command.resolution.command?.entrypoint).toBe(fixture.script);
      expect(command.env).toMatchObject({ HOME: "scoped", MARKER: "profile" });
      // These real npm forms SETLOCAL then endLocal: temporary assignments do not leak.
      expect(command.env.FIXTURE).toBeUndefined();
      expect(command.env.PATHEXT).toBe(kind === "node-current" ? ".COM;.EXE;" : ".COM;.JS;.EXE;");
    },
  );

  it("executes the chosen entry with exact argv and profile env, without a shell", () => {
    const fixture = installed();
    const args = [
      "",
      "with spaces",
      'a"b',
      "tail\\",
      "line1\nline2",
      "%USER%",
      "!&|^<>()",
      "日本語",
    ];
    const command = prepareHarnessCommand(
      fixture.shim,
      args,
      { PATH: "", HOME: "scratch", MARKER: "selected-account" },
      "win32",
    );
    const result = spawnSync(command.binary, command.args, { env: command.env, encoding: "utf8" });
    expect(result.status, result.stderr).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual({
      args,
      home: "scratch",
      marker: "selected-account",
    });
  });

  it("uses PATH Node when no adjacent interpreter exists, and invalidates on script/runtime changes", () => {
    const fixture = installed();
    const path = fixture.prefix;
    const first = harnessBinaryIdentityOnPath("tool", path, "win32");
    expect(first?.path).toBe(fixture.script);
    expect(first?.interpreter?.path).toBe(fixture.node);
    writeFileSync(fixture.script, readFileSync(fixture.script, "utf8") + "// changed\n");
    expect(harnessBinaryIdentityOnPath("tool", path, "win32")).not.toEqual(first);
    const runtimeDir = join(root, "runtime");
    mkdirSync(runtimeDir);
    const otherNode = join(runtimeDir, "node.exe");
    copyFileSync(fixture.node, otherNode);
    rmSync(fixture.node);
    const resolved = prepareHarnessCommand(fixture.shim, [], { PATH: runtimeDir }, "win32");
    expect(resolved.binary).toBe(otherNode);
  });

  it("honors an explicitly selected extensionless Node entrypoint", () => {
    const fixture = installed();
    const entry = join(fixture.packageRoot, "bin", "extensionless");
    copyFileSync(fixture.script, entry);
    const command = prepareHarnessCommand(entry, ["argument"], { PATH: fixture.prefix }, "win32");
    expect(command.binary).toBe(fixture.node);
    expect(command.args).toEqual([entry, "argument"]);
  });

  it("resolves a declared native package bin without any vendor layout map", () => {
    const fixture = installed("native");
    const command = prepareHarnessCommand("tool", ["--version"], { PATH: fixture.prefix }, "win32");
    expect(command.binary).toBe(fixture.script);
    expect(command.args).toEqual(["--version"]);
    expect(command.resolution.command?.interpreter).toBeUndefined();
  });

  it("does not bypass a customized wrapper even when its last line targets a package bin", () => {
    const fixture = installed();
    writeFileSync(fixture.shim, `@SET EXTRA=custom\r\n${readFileSync(fixture.shim, "utf8")}`);
    expect(resolveHarnessCommandOnPath("tool", fixture.prefix, "win32").command).toBeNull();
    expect(() =>
      prepareHarnessCommand(fixture.shim, [], { PATH: fixture.prefix }, "win32"),
    ).toThrow("supported standard npm launcher");
    writeFileSync(
      fixture.shim,
      readFileSync(join(fixtures, "node.cmd"), "utf8").replace(/\r?\n/g, "\r\n"),
    );
    expect(resolveHarnessCommandOnPath("tool", fixture.prefix, "win32").command?.entrypoint).toBe(
      fixture.script,
    );
  });

  it("rejects a mismatched npm declaration and accepts the string-bin shorthand", () => {
    const fixture = installed();
    const metadata = join(fixture.packageRoot, "package.json");
    writeFileSync(
      metadata,
      JSON.stringify({ name: "@fixture/tool", bin: { other: "bin/tool.cjs" } }),
    );
    expect(resolveHarnessCommandOnPath("tool", fixture.prefix, "win32").command).toBeNull();
    writeFileSync(metadata, JSON.stringify({ name: "@fixture/tool", bin: "bin/tool.cjs" }));
    expect(resolveHarnessCommandOnPath("tool", fixture.prefix, "win32").command?.entrypoint).toBe(
      fixture.script,
    );
  });

  it("keeps an explicit broken path exact and discloses a viable unpinned fallback", () => {
    const preferred = join(root, "first");
    mkdirSync(preferred);
    const broken = join(preferred, "tool.exe");
    symlinkSync(join(root, "missing.exe"), broken);
    const fallback = installed();
    const path = [preferred, fallback.prefix].join(delimiter);
    const resolved = resolveHarnessCommandOnPath("tool", path, "win32");
    expect(resolved.command?.entrypoint).toBe(fallback.script);
    expect(resolved.advisory).toContain(broken);
    expect(resolved.advisory).toContain(fallback.script);
    expect(resolveHarnessCommandOnPath(broken, path, "win32").command).toBeNull();
  });
});

it("fills only missing baseline OS identity, without deriving it from a profile HOME", () => {
  const actual = userInfo().username;
  expect(
    harnessRuntimeEnv(
      { HOME: join(root, "not-an-os-account"), USER: "", LOGNAME: "  " },
      "/absent/node",
    ),
  ).toMatchObject({ USER: actual, LOGNAME: actual });
  expect(
    harnessRuntimeEnv({ USER: "supplied", LOGNAME: "also supplied" }, "/absent/node"),
  ).toMatchObject({ USER: "supplied", LOGNAME: "also supplied" });
  const patched = composeSpawnEnv("clean", { USER: null, LOGNAME: "", PATH: "explicit" });
  expect(patched.USER).toBeUndefined();
  expect(patched.LOGNAME).toBe("");
  expect(patched.PATH).toBe("explicit");
});

it("uses the existing Windows tree terminator before killing a live wrapper", () => {
  const kill = vi.fn();
  const tree = vi.fn(() => ({ status: "killed" as const, pid: 123 }));
  const child = { pid: 123, exitCode: null, signalCode: null, kill };
  expect(killOwnedProcessTree(child as never, "SIGTERM", "win32", tree)).toEqual({
    status: "killed",
    pid: 123,
  });
  expect(tree).toHaveBeenCalledWith(123);
  expect(kill).not.toHaveBeenCalled();
  killOwnedProcessTree(child as never, "SIGTERM", "darwin", tree);
  expect(kill).toHaveBeenCalledWith("SIGTERM");
});
